### ISSUE TITLE
A broken ore dictionary registration

### ISSUE THREAD

**Issue by jokish63** [Kashdeya/SimpleUpgrades#1]
A broken ore dictionary registration with name dustIron has occurred. It adds an item (type: class net.minecraft.item.Item) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Simple Upgrades report it to them!

the same appears for Gold and Obsidian

Log: http://paste.ee/p/ubZFZ

**Comment by Kashdeya** [comment]
has been fixed in v1.0.1
