### ISSUE TITLE
ores spawning  without mods installed

### ISSUE THREAD

**Issue by athenashavoc** [Kashdeya/SimpleUpgrades#11]
I do not have AbyssalCraft or Tinker's installed but Antimatter, Coralium, and Molten Dirt crystals spawn in the overworld.

ver 1.0.9

Also, texture form Coralium is missing but this is probably because I don't have AbyssalCraft

[images](http://imgur.com/a/xsX2g)

**Comment by Kashdeya** [comment]
Do you have them turned off in the config file?

**Comment by athenashavoc** [comment]
I do now. 

I think I misunderstood the config. It says ores will spawn if a mod is installed. I assumed that if I did not have the mods installed, they would not spawn.

They are off in the config now and everything is good.

**Comment by Kashdeya** [comment]
ok cool. I will update the config to explain better in next update.
