### ISSUE TITLE
Flickering sky with night vision effects

### ISSUE THREAD

**Issue by tommyTT** [Kashdeya/SimpleUpgrades#12]
When putting the wither or dragon armor on and the night vision becomes active, the sky starts flickering. This is very distracting and doesn't happen with a normal night vision potion. None of the video settings have been changed and there are no other mods installed. 

See log and example:
https://gfycat.com/IllAchingGoldenretriever
http://pastebin.com/PydVHzEj

**Comment by Kashdeya** [comment]
this issue has been fixed in next update, Thank you for reporting.
