### ISSUE TITLE
Wither Helmet and Boots have same recipe

### ISSUE THREAD

**Issue by tommyTT** [Kashdeya/SimpleUpgrades#13]
Both the Recipes for the helmet and boots of the Wither armor are identical, so it is only possible to craft the helmet. I think the recipe for the boots should have the nether star on the same level as the normal skeleton skulls.

http://imgur.com/a/VInAI
http://pastebin.com/PydVHzEj

**Comment by Kashdeya** [comment]
this issue has been fixed in next update, Thank you for reporting.
