### ISSUE TITLE
Weird arm movement when swinging while wearing Dragon Armor

### ISSUE THREAD

**Issue by tommyTT** [Kashdeya/SimpleUpgrades#14]
When I have the dragon armor on and i try to swing a sword it doesn't have the normal swing action but the arm simply disappears and reappears (see video for better description). This is very irritating when in combat.

https://gfycat.com/AngelicHospitableBillygoat
http://pastebin.com/PydVHzEj

**Comment by Kashdeya** [comment]
Looking into this one.

**Comment by Kashdeya** [comment]
Problem has been fixed in next release.
