### ISSUE TITLE
Massive framerate lag

### ISSUE THREAD

**Issue by MJRamon** [Kashdeya/SimpleUpgrades#15]
Whenever I add this mod, it lags my framerate (from 100+ FPS to 5), doesn't matter, if chunks were generated before or not.
Even if I turn EVERYTHING to false, it keeps lagging the same way.

**Comment by Kashdeya** [comment]
Replied to this on CurseForge. Please provide a log or something to prove this. It is in a lot of packs and not one modpack dev has came to me about this issue.
