### ISSUE TITLE
Server Crashes with NoClassDefFoundException and Version 1.0.12

### ISSUE THREAD

**Issue by tommyTT** [Kashdeya/SimpleUpgrades#16]
I tried using the newest version 1.0.12 of the mod and on the client side, everything is okay. However on the server side it always crashes with a NoClassDefFoundException because it can't find the class net/minecraftforge/client/event/GuiScreenEvent$PotionShiftEvent.

SimpleUpgrades is the only mod on my test server. Version 1.0.11 started without problems.

http://pastebin.com/Yvs7j3E1

**Comment by Kashdeya** [comment]
thank you. i forgot to disable that before i sent out the update.
