### ISSUE TITLE
potion effects of armors don't work in servers

### ISSUE THREAD

**Issue by aoface** [Kashdeya/SimpleUpgrades#17]
Only icons in inventory page, but not actually effects as so as no icon on up right corner.
Mod version is 1.0.13 and forge version is 1.9-forge1.9-12.16.1.1887.

**Comment by Kashdeya** [comment]
I have the effects turned off on the armor for ingame, this was a request from a pack maker for his pack/server. so the effects are still applied but do not show while in game only in your inventory.

**Comment by Kashdeya** [comment]
issues has been fixed.
