### ISSUE TITLE
Granite, Diorite, Andesite Tools give no Block back

### ISSUE THREAD

**Issue by jokish63** [Kashdeya/SimpleUpgrades#2]
As I used your Tools for mining i've noticed that there is no Blockdrop. 
Can you check that please. (the game is not crash just no drop)

best regards jokish

**Comment by Kashdeya** [comment]
So it only happens with the Pickaxes?

**Comment by jokish63** [comment]
Thank you for the fast response
all the tools I've used for now, works well so far.
If I find some (hopefully not :) I inform you.
best regards jokish
