### ISSUE TITLE
OreDictionary Support

### ISSUE THREAD

**Issue by InkDragon** [Kashdeya/SimpleUpgrades#21]
please add ore dictionary support so that you buckets of water, cactus fruit, flour and dough are compatible with pam's harvestcraft.

**Comment by Kashdeya** [comment]
there is ore dict support for most of the mod, but not ever mod uses the same oredict names. i will look into this when pams gets updated to 1.9.4.

**Comment by InkDragon** [comment]
pam's uses foodFlour, foodDough, cropCactusfruit for sure
I look forward to seeing more from the mod in the future
