### ISSUE TITLE
Wooden Bucket bug

### ISSUE THREAD

**Issue by APolarBaer** [Kashdeya/SimpleUpgrades#22]
currently making a 1.9.4 modpack and when i use the wooden bucket for water as soon as i grab the source it turns into a iron water bucket, ill try to look around more and see if its a different mod doing it but i thought i would post here just in case its not
![screenshot 2016-06-06 17 59 58](https://cloud.githubusercontent.com/assets/19779692/15839273/79c4b4e8-2c10-11e6-9ad7-291870ce4a8d.png)
![screenshot 2016-06-06 18 00 01](https://cloud.githubusercontent.com/assets/19779692/15839272/79c36e6c-2c10-11e6-81a6-c2e921806d6f.png)

**Comment by Kashdeya** [comment]
yes this will be fixed in the next update. the version that is out now is just a test build.

**Comment by APolarBaer** [comment]
oh, alrighty
