### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by yepidoodles** [Kashdeya/SimpleUpgrades#28]
So, this is an odd one, I have a crash when starting up a single player world, the crash report indicates that Simple Upgrades and Pam's Harvestcraft world gen are clashing, however, I have another modpack I just updated with both mods installed and they were just fine.

Report:
http://www.codesend.com/view/aae3e239438c81f17c352868a8e17dc8/

- Alice
DragonTechMC

**Comment by Kashdeya** [comment]
Turn the salt off on one of them. this will be fixed in the full release.
