### ISSUE TITLE
Mixing Bowl and Dough Recipe

### ISSUE THREAD

**Issue by jokish63** [Kashdeya/SimpleUpgrades#29]
I have a small problem. I would like to turn off the mixing bowl and the dough recipe, because I do not need them, because I'm don't use your Foodstuff except the Fries, but I cant' find any entry in the config file
The Mixing Bowl recipe is also the same as ShetiPhians Plant Pot recipe in the terraqueous mod which is not craftable right now.
It would be great if you both could clarify the conflicting recipe
Best regard jokish

**Comment by Kashdeya** [comment]
I will not change my recipes as of right now.
