### ISSUE TITLE
End Bug

### ISSUE THREAD

**Issue by Myknakryu** [Kashdeya/SimpleUpgrades#3]
I created portal to end to try if it works. After entering into end game crashed.

Here are logs:
http://pastebin.com/TNVi7M8J

**Comment by Myknakryu** [comment]
Ok, I've solved the problem. Just needed to disable Flat bedrock. Mod tried to generate bedrock in end Dimmension.

**Comment by Kashdeya** [comment]
Thank you fro reporting it. I will add it to the list of things to fix for next update.
