### ISSUE TITLE
Server Crashes with NoClassDefFoundException in version 2.0.0

### ISSUE THREAD

**Issue by DreadBoy** [Kashdeya/SimpleUpgrades#30]
Crash is very similar to issue #16 , except it's happening in version 2.0.0. Crash report: https://gist.github.com/DreadBoy/e7baf002c000ff6b86ce41c74fad0206

**Comment by APolarBaer** [comment]
i get this aswell, https://gist.github.com/APolarBaer/65764f78734f6cb928731ed6dd96eb53

**Comment by Kashdeya** [comment]
This has been fixed in the full release. Thank you for reporting.

**Comment by APolarBaer** [comment]
any ETAs on the release?

**Comment by Kashdeya** [comment]
well yes and no. i want to get it out asap but at the same time i am working on a handful of projects. as of right now stable 1.9.4 is about 80% done. other then that idk. but it will be out.

**Comment by APolarBaer** [comment]
Okay, thanks for the response owo

**Comment by APolarBaer** [comment]
was the release today the one this would be fixed in? :P

**Comment by Kashdeya** [comment]
v2.0.6 should not crash for you. if it does please let me know.

**Comment by APolarBaer** [comment]
i shall, thank you~

**Comment by DreadBoy** [comment]
I can confirm 2.0.7 doesn't crash server any more.
