### ISSUE TITLE
Description: Exception in server tick loop

### ISSUE THREAD

**Issue by derSchotte** [Kashdeya/SimpleUpgrades#31]
Hi, i try to setup a server but with your Mod it crashes on loading.
if im correct, you fixed this already for 1.9

Minecraft: 1.9.4 / Forge 12.17.0.1987 / SimpleUpgrades 1.9.4-2.0.0

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.5.52-ex19.jar)
  FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  CoreMod (Aroma1997Core-1.9.4-1.0.7.0.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.9.4-2.0.8.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  MMFMLCorePlugin (MultiMine-1.9.4.jar)
  TransformerLoader (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar)
  Crafting Harmonics Core (craftingharmonics-1.9.4-1.5.0.33.jar)
  AppleCore (AppleCore-mc1.9.4-1.3.4.jar)
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  LoadingPlugin (Quark-beta-29.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 26.06.16 21:43
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiScreenEvent$PotionShiftEvent
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:555)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:91)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:321)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiScreenEvent$PotionShiftEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getDeclaredMethods(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:346)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:524)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.GuiScreenEvent$PotionShiftEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 31 more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiScreenEvent
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 33 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.GuiScreenEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1257107240 bytes (1198 MB) / 1549795328 bytes (1478 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 1 total; -Xmx6144M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.28 Powered by Forge 12.17.0.1987 156 mods loaded, 156 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (minecraft_server.jar) 
	UC	Forge{12.17.0.1987} [Minecraft Forge] (minecraft_server.jar) 
	UC	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.0.7.0.jar) 
	UC	buildingbrickshooks{1.9.4-2.0.8} [Building Bricks Hooks] (minecraft.jar) 
	UC	OpenComputers|Core{1.6.0.2-beta.3} [OpenComputers (Core)] (minecraft.jar) 
	UC	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.9.4-alpha-1.0.0a.jar) 
	UC	JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar) 
	UC	abyssalcraft{1.9.2.1} [AbyssalCraft] (AbyssalCraft-1.9.4-1.9.2.1.jar) 
	UC	actuallyadditions{1.9.4-r45} [Actually Additions] (ActuallyAdditions-1.9.4-r45.jar) 
	UC	additionalbanners{1.2.0.17} [Additional Banners] (AdditionalBanners-1.9.4-1.2.0.18.jar) 
	UC	advancedcapes{4.0} [Advanced Capes] (advancedcapes-4.0.jar) 
	UC	AppleCore{1.3.4} [AppleCore] (AppleCore-mc1.9.4-1.3.4.jar) 
	UC	armorplus{1.9.4-3.1.1.0} [ArmorPlus] (ArmorPlus1.9.4-3.1.1.0.jar) 
	UC	Aroma1997CoreHelper{1.0.7.0} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.0.7.0.jar) 
	UC	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UC	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UC	bagginses{2.4.2d} [Bagginses] (Bagginses-1.9.4-2.4.2d.jar) 
	UC	basemetals{2.3.2} [Base Metals] (BaseMetals_1.9.4-2.3.2.6.jar) 
	UC	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UC	rarmor{0.8.1} [Rarmor] (Rarmor-0.8.1.jar) 
	UC	baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar) 
	UC	bdlib{1.12.0.2} [BD Lib] (bdlib-1.12.0.2-mc1.9.4.jar) 
	UC	BetterAchievements{0.3.0.26} [Better Achievements] (BetterAchievements-1.9.4-0.3.0.26.jar) 
	UC	betterbuilderswands{0.6.2} [Better Builder's Wands] (BetterBuildersWands-0.6.2-1.9.4r132+a2243db.jar) 
	UC	BiomesOPlenty{4.1.0.2031} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2031-universal.jar) 
	UC	BloodMagic{1.9.4-2.0.2-46} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-46.jar) 
	UC	BloodArsenal{1.9.4-2.0.0-5} [Blood Arsenal] (BloodArsenal-1.9.4-2.0.0-5.jar) 
	UC	bookshelf{1.2.3.279} [Bookshelf] (Bookshelf-1.9.4-1.2.3.279.jar) 
	UC	Botania{r1.8-310} [Botania] (Botania-unofficial.r1.8-310.jar) 
	UC	Quark{beta-29} [Quark] (Quark-beta-29.jar) 
	UC	buildingbricks{1.9.4-2.0.8} [Building Bricks] (BuildingBricks-1.9.4-2.0.8.jar) 
	UC	Chameleon{1.9.4-2.1.5} [Chameleon] (Chameleon-1.9.4-2.1.5.jar) 
	UC	chisel{@VERSION@} [Chisel] (Chisel-MC1.9.4-0.0.5.29.jar) 
	UC	chiselsandbits{10.10} [Chisels & Bits] (chiselsandbits-10.10.jar) 
	UC	cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3.jar) 
	UC	colossalchests{1.3.5} [Colossal Chests] (ColossalChests-1.9.4-1.3.5.jar) 
	UC	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9.4.jar) 
	UC	compasscoords{1.9.4-3.1.4} [Compass Co-ords] (CompassCoords-1.9.4-3.1.4.jar) 
	UC	cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar) 
	UC	correlatedpotentialistics{1.1.2} [Correlated Potentialistics] (CorrelatedPotentialistics-1.1.2.jar) 
	UC	craftablenametags{1.2} [Craftable Name Tags] (craftablenametags-1.2.jar) 
	UC	craftingcraft{4.0.3} [CraftingCraft] (craftingcraft-mc1.9.4-4.0.3.jar) 
	UC	NashornLib{1.9.4-1.8.77-1.3.0} [Nashorn Library] (NashornLib-1.9.4-1.8.77-1.3.0.7.jar) 
	UC	craftingharmonics{1.9.4-1.5.0} [Crafting Harmonics] (craftingharmonics-1.9.4-1.5.0.33.jar) 
	UC	craftingtweaks{5.0.6} [Crafting Tweaks] (craftingtweaks-mc1.9.4-5.0.6.jar) 
	UC	wonderfulwands{2.1.0} [Wonderful Wands] (CyanosWonderfulWands_1.9.4-2.1.0.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	DarkUtils{1.1.2.52} [Dark Utilities] (DarkUtilities-1.9.4-1.1.2.55.jar) 
	UC	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UC	deepresonance{1.2.0beta35} [DeepResonance] (deepresonance-1.9.4-1.2.0beta35.jar) 
	UC	dldungeonsjdg{1.8.13} [Doomlike Dungeons] (DoomlikeDungeons-1.8.13-MC1.9.4.jar) 
	UC	easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
	UC	poweradvantage{2.2.1} [Power Advantage] (PowerAdvantage_1.9.4-2.2.1.jar) 
	UC	electricadvantage{2.1.0} [Electric Advantage] (ElectricAdvantage_1.9-2.1.0.jar) 
	UC	enchiridion{3.1.5} [Enchiridion] (Enchiridion-1.9.4-3.1.5.jar) 
	UC	endercompass{1.2.3.1} [Ender Compass] (EnderCompass-1.9.x-1.2.3.1.jar) 
	UC	endercore{1.9.4-0.4.0.26-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.26-alpha.jar) 
	UC	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UC	EnderIO{1.9.4-3.0.0.46_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.46_alpha.jar) 
	UC	enderrift{1.0.1} [Ender-Rift] (EnderRift-1.9.4-1.0.1.jar) 
	UC	shetiphiancore{3.2.6} [ShetiPhian-Core] (shetiphiancore-1.9.4-3.2.6.jar) 
	UC	endertanks{1.3.6} [EnderTanks] (endertanks-1.9.4-1.3.6.jar) 
	UC	enderthing{0.6.8} [Enderthing] (enderthing-1.9.4-0.6.8.jar) 
	UC	enderutilities{0.6.4} [Ender Utilities] (enderutilities-1.9.4-0.6.4.jar) 
	UC	EnderZoo{1.9.4-1.2.2.40} [Ender Zoo] (EnderZoo-1.9.4-1.2.2.40.jar) 
	UC	ValkyrieLib{1.9.4-0.9.12} [Valkyrie Lib] (valkyrielib-1.9.4-0.9.12.jar) 
	UC	EnvironmentalTech{1.9.4-0.9.4e} [Environmental Tech] (environmentaltech-1.9.4-0.9.4e.jar) 
	UC	evilcraft{0.10.2} [EvilCraft] (EvilCraft-1.9.4-0.10.2.jar) 
	UC	ExtraBitManipulation{1.9-2.1.2} [Extra Bit Manipulation] (ExtraBitManipulation-1.9.4-2.1.0.jar) 
	UC	golems{5.01} [Extra Golems] (ExtraGolems[1.9.4]-5.01.jar) 
	UC	IC2{2.5.52-ex19} [IndustrialCraft 2] (industrialcraft-2-2.5.52-ex19.jar) 
	UC	OpenComputers{1.6.0.2-beta.3} [OpenComputers] (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar) 
	UC	FFS{1.9.4-1.6.3-b23} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.6.3-b23.jar) 
	UC	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-MC1.9.4-1.7.jar) 
	UC	flatcoloredblocks{mc1.9.4-v3.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.9.4-v3.1.jar) 
	UC	fluxducts{1.0.4} [Flux Ducts] (fluxducts-mc1.9.4-1.0.4.jar) 
	UC	forestry{5.0.23.170} [Forestry] (forestry_1.9.4-5.0.23.170.jar) 
	UC	SilentLib{1.0.10} [Silent Lib] (SilentLib-1.9.4-1.0.10-18.jar) 
	UC	FunOres{1.2.7} [Fun Ores] (FunOres-1.9.4-1.2.7-68.jar) 
	UC	furnus{1.82} [Furnus] (Furnus-1.9.4-1.82.jar) 
	UC	pressure{1.3.1.2} [Pressure Pipes] (pressure-1.3.1.2-mc1.9.4.jar) 
	UC	advgenerators{0.9.20.2} [Advanced Generators] (generators-0.9.20.2-mc1.9.4.jar) 
	UC	glass_shards{1.6.2} [Glass Shards] (glass_shards_mc1.9.4-1.6.2.jar) 
	UC	Harvest{1.9.4-1.0.1-6} [Harvest] (Harvest-1.9.4-1.0.1-6.jar) 
	UC	HelpFixer{1.3.14} [HelpFixer] (HelpFixer-1.9.4-1.3.14.jar) 
	UC	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7.jar) 
	UC	ice_shards{1.4.2} [Ice Shards] (ice_shards_mc1.9.4-1.4.2.jar) 
	UC	IGWMod{1.3.0-5} [In-Game wiki Mod] (IGW-Mod-1.9.4-1.3.0-5-universal.jar) 
	UC	integrateddynamics{0.3.10} [Integrated Dynamics] (IntegratedDynamics-1.9.4-0.3.10.jar) 
	UC	InventoryPets{1.4.7.1} [Inventory Pets] (inventorypets-1.9.4-1.4.7.1.jar) 
	UC	IronChest{6.0.146.788} [Iron Chest] (ironchest-1.9.4-6.0.146.788.jar) 
	UC	journeymap{1.9.4-5.2.3} [JourneyMap] (journeymap-1.9.4-5.2.3-unlimited.jar) 
	UC	fyberbackpack{1.0.2} [Just Backpacks] (justbackpacks-mc1.9.4-1.0.2.jar) 
	UC	jet_packs{1.0.0} [Just JetPacks] (JustJetpacks-1.9.4-1.0.0.jar) 
	UC	lteleporters{1.1.2} [Lemon's Simple Teleporters] (LemonsSimpleTeleporters-1.1.2-MC1.9.4.jar) 
	UC	lightningcraft{2.3.3} [LightningCraft] (lightningcraft-2.3.3-[1.9.4].jar) 
	UC	LunatriusCore{1.1.2.35} [LunatriusCore] (LunatriusCore-1.9.4-1.1.2.35-universal.jar) 
	UC	mantle{1.9.4-0.10.2.jenkins149} [Mantle] (Mantle-1.9.4-0.10.2.jar) 
	UC	miab{1.4.2} [Meme in a bottle] (MemeInABottle-1.4.2 1.9.4.jar) 
	UC	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UC	modifiable_armor{2.0.2} [Modifiable Armor 2] (ModifiableArmor2-1.9.4-2.0.2.jar) 
	UC	morefood{1.15d} [More Foods] (morefood-1.9.4-1909-1.16.jar) 
	UC	Morpheus{1.9.4-3.1.5} [Morpheus] (Morpheus-1.9.4-3.1.5.jar) 
	UC	mputils{1.0.0} [ModPack Utilities] (mputils-1.9.4-1.0.1.jar) 
	UC	mpbasic{1.0.0} [ModPack Basic Tools] (mpbasic-1.9.4-1.0.0.jar) 
	UC	AS_MultiMine{1.5.3} [Multi Mine] (MultiMine-1.9.4.jar) 
	UC	multistorage{1.1.3} [Multi-Storage] (multistorage-1.9.4-1.1.3.jar) 
	UC	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UC	notenoughwands{1.3.5} [Not Enough Wands] (notenoughwands-1.9.4-1.3.5.jar) 
	UC	fodc{1.8.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.2.jar) 
	UC	orespawn{1.0.3} [Ore Spawn] (OreSpawn_1.9.4-1.0.3.jar) 
	UC	packingtape{0.5.1} [Packing Tape] (PackingTape-1.9.4-0.5.1.jar) 
	UC	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar) 
	UC	pedestal{1.9.4-1.0.1} [Pedestal] (pedestal-1.9.4-1.0.1.jar) 
	UC	planttech{1.6.0} [Planttech] (planttech-1.6.0 - 1.9.4.jar) 
	UC	playerrugs{1.9.4-1.3.2} [Player Rugs] (PlayerRugs-1.9.4-1.3.2.jar) 
	UC	progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar) 
	UC	Psi{r1.0-35} [Psi] (Psi-r1.0-35.jar) 
	UC	quantumflux{2.0.7} [QuantumFlux] (quantumflux-1.9.4-2.0.7.jar) 
	UC	reborncore{2.5.4.47} [RebornCore] (RebornCore-1.9.4-2.5.4.47-universal.jar) 
	UC	QuantumStorage{3.1.0} [QuantumStorage] (QuantumStorage-1.9.4-3.1.0.jar) 
	UC	randomthings{3.7.3} [Random Things] (RandomThings-MC1.9.4-3.7.3.jar) 
	UC	reborncore-mcmultipart{2.5.4.47} [reborncore-MCMultiPart] (RebornCore-1.9.4-2.5.4.47-universal.jar) 
	UC	xreliquary{1.9.4-1.3.2.390} [Reliquary] (Reliquary-1.9.4-1.3.2.390.jar) 
	UC	ResourcefulCrops{1.9.4-1.3.2-54} [ResourcefulCrops] (ResourcefulCrops-1.9.4-1.3.2-54.jar) 
	UC	rftools{4.66} [RFTools] (rftools-1.9.4-4.66.jar) 
	UC	rftoolsdim{4.30beta43} [RFTools Dimensions] (rftoolsdim-1.9.4-4.30beta43.jar) 
	UC	Roguelike{1.5.3} [Roguelike Dungeons] (RoguelikeDungeons-1.9.4-1.5.3.jar) 
	UC	AS_Ruins{16.1} [Ruins Spawning System] (Ruins-1.9.4.jar) 
	UC	shadowmc{3.3.9} [ShadowMC] (ShadowMC-1.9.4-3.3.9.jar) 
	UC	simplegrinder{1.242.A194} [Simple Grinder] (SimpleGrinder-1.262.R194.jar) 
	UE	SimpleUpgrades{2.0.0} [SimpleUpgrades] (simpleupgrades-1.9.4-2.0.0-release.jar) 
	UC	SleepingBag{1.2.1} [Sleeping Bag] (SleepingBag-1.9.4-1.2.1.jar) 
	UC	soulshardstow{1.9.4-2.4.5-33} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9.4-2.4.5-33.jar) 
	UC	SpiceOfLife{1.3.3} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.3.jar) 
	UC	Stackie{1.6.0.42} [Stackie] (Stackie-1.9.4-1.6.0.42-universal.jar) 
	UC	steamadvantage{2.1.0} [Steam Advantage] (SteamAdvantage_1.9.4-2.1.0.jar) 
	UC	StorageDrawers{1.9.4-3.1.10} [Storage Drawers] (StorageDrawers-1.9.4-3.1.10.jar) 
	UC	storagenetwork{1.12.0} [Storage Network] (StorageNetwork-1.9.4-1.12.0.jar) 
	UC	tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct] (TConstruct-1.9.4-2.3.3.jar) 
	UC	territorychevsky{b16} [Territorial Dealings] (TerritorialDealings_1.9_b16.jar) 
	UC	tipalert{1.0.0} [Helpful Tip Alerts] (tipalert-1.9.4-1.0.0.jar) 
	UC	tombmanygraves{1.9.4-2.1.5} [Tomb Many Graves] (TombManyGraves-1.9.4-2.1.5.jar) 
	UC	totemic{1.9.4-0.7.6} [Totemic] (Totemic-1.9.4-0.7.6.jar) 
	UC	underphangables{1.0.2} [Underp Hangables] (underphangables-1.10.0-1.0.2.jar) 
	UC	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.4.jar) 
	UC	vampirism{1.0.0-Alpha+06-25-00-29} [Vampirism] (Vampirism-1.9.4_1.10-1.0.0-Alpha+06-25-00-29.jar) 
	UC	teamlapen-lib{1.0.0-Alpha+06-25-00-29} [TeamLapen Library] (Vampirism-1.9.4_1.10-1.0.0-Alpha+06-25-00-29.jar) 
	UC	VeinMiner{0.33.1_1.9-da0f6cb} [Vein Miner] (VeinMiner-0.33.1-1.9r554+da0f6cb.jar) 
	UC	VeinMinerModSupport{0.33.1_1.9-da0f6cb} [Mod Support] (VeinMiner-0.33.1-1.9r554+da0f6cb.jar) 
	UC	veinminermodintegration{1.7.10-0.2.0} [Veinminer Mod Integration] (veinminermodintegration-0.6.0-1.9.4r29+2f88da6.jar) 
	UC	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UC	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9.4-2.2.1.192.jar) 
	UC	wawla{2.2.1.188} [What Are We Looking At] (Wawla-1.9.4-2.2.1.192.jar) 
	UC	YALSM{2.1.6} [Yet Another Leather Smelting Mod] (yalsm-2.1.6-mc1.9.4.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.5.52-ex19.jar)
  
FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  com.olafski.fastleafdecay.FldTransformer
CoreMod (Aroma1997Core-1.9.4-1.0.7.0.jar)
  
LoadingPluginBuildingBricks (BuildingBricks-1.9.4-2.0.8.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  shetiphian.core.asm.ClassTransformer
MMFMLCorePlugin (MultiMine-1.9.4.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
TransformerLoader (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar)
  li.cil.oc.common.asm.ClassTransformer
Crafting Harmonics Core (craftingharmonics-1.9.4-1.5.0.33.jar)
  org.winterblade.minecraft.harmony.asm.PotionRemovedHookTransformer
AppleCore (AppleCore-mc1.9.4-1.3.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
LoadingPlugin (Quark-beta-29.jar)
  vazkii.quark.base.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by Kashdeya** [comment]
has been fixed in newest version
