### ISSUE TITLE
Crash on startup!

### ISSUE THREAD

**Issue by KristjanKr** [Kashdeya/SimpleUpgrades#32]
SimpleUpgrades: simpleupgrades-1.10.0-2.0.5-release.jar
Forge: forge 1.10-12.18.0.2000 or simply build 2000 for mincraft 1.10

crash log:
http://paste.ee/p/z8D6p

What happens: crashes when starting game with crashlog mentioned before.

**Comment by Kashdeya** [comment]
working on it now. hope to have a fix up asap.

**Comment by Kashdeya** [comment]
just pushed out v2.0.6 for 1.9.4 & 1.10. 
Fixed crash when Base Metals is not installed in modpack.
Base Metals now turned off by DEFAULT.
