### ISSUE TITLE
Crash on startup, MC 1.10

### ISSUE THREAD

**Issue by xhaavardx** [Kashdeya/SimpleUpgrades#33]
Game crashes on startup

Client setup:
- Minecraft 1.10
- Simple Upgrades 2.0.6
- Forge 12.18.0.2000

Crash log:
https://paste.ee/p/D2a5o

**Comment by Kashdeya** [comment]
this crash is caused by another mod in the pack. most likly a mod that does the same thing as this one.

**Comment by xhaavardx** [comment]
What exactly am I looking for? I see references to smelting ore and furnace recipes.

**Comment by Kashdeya** [comment]
um idk, you are using a lot of mods that i have not tested with. so I would suggest removing one mod at a time to figure out which one it is and let me know so i can test it on my test build and see if I can fix it or if they need to fix their mod.

**Comment by xhaavardx** [comment]
Could you mention which mods you HAVE tested with? That might reduce the amount of time it takes for me to pin down the problem.

**Comment by Kashdeya** [comment]
when 2.0.7 gets pushed please try it. that should fix the problem.

**Comment by xhaavardx** [comment]
Thanks! It works now!
