### ISSUE TITLE
NPE on worldgen for 2.0.7 on MC 1.10.2

### ISSUE THREAD

**Issue by LlubNek** [Kashdeya/SimpleUpgrades#35]
Minecraft 1.10.2 crashes (but fails to exit properly) during worldgen with simpleupgrades-1.10.0-2.0.7-release.jar and Forge 12.8.0.2002.

Here's the important bit:
`java.lang.NullPointerException: Exception in server tick loop
	at com.kashdeya.simpleupgrades.world.worldgen.runGenerator(worldgen.java:355)
	at com.kashdeya.simpleupgrades.world.worldgen.generate(worldgen.java:383)
`

Here's the crash report:
http://pastebin.com/ADqMuKUR

Here's the game output (killed it with task manager):
http://pastebin.com/GpmqFATN

**Comment by Kashdeya** [comment]
I will look into this when i start the 1.10.2 update. Thank you

**Comment by Kashdeya** [comment]
Could not duplicate problem in 1.10.2. Please try the newest version on curse.

**Comment by LlubNek** [comment]
Here it is again with simpleupgrades-1.10.0-2.0.11-release.jar with Forge 12.18.0.2005 and Minecraft 1.10.2.  Again, killed it with task manager.
crash report:  http://pastebin.com/qPtX1jif
latest.log:  http://pastebin.com/7ubetZUs

**Comment by LlubNek** [comment]
If you really can't duplicate this otherwise I could send you a zip with my configs and mods.

**Comment by Kashdeya** [comment]
yes please send me your files cause i have this in 5 modpacks and not one of them are seeing this issue.

**Comment by Kashdeya** [comment]
If you need to join my curse group and send me the info there or add me to curse.

**Comment by LlubNek** [comment]
Not using curse myself.  I've included the lightloader and forge installers.  Should probably have mentioned this earlier (pretty sure it shows up in the log somewhere), but I've been using the BOP world type, so try it with that.

https://mega.nz/#!3oNg1Axb!0pI3KCmPgJM6ILaXI24rnwRLXfLMD1b7GqRiugoY5Us

**Comment by Kashdeya** [comment]
ok i found the problem.  Open 1.SimpleUpgrades.cfg and scroll to the very bottom and change that to false. in the next version I will move that to the worldgen cfg.

**Comment by LlubNek** [comment]
Looks like that did the trick.  Thanks :)
