### ISSUE TITLE
[Client Crash]Torch with stone tool rod

### ISSUE THREAD

**Issue by APolarBaer** [Kashdeya/SimpleUpgrades#36]
i can make them but when i place them it gives me this big render error

http://pastebin.com/u7nHHXT2

1.9.4
SU 2.0.7

**Comment by APolarBaer** [comment]
looking at the torch with your crosshair, you can be near it, it might be waila

**Comment by Kashdeya** [comment]
1.9.4-2.0.7-HotFix will be out soon.

**Comment by APolarBaer** [comment]
thanks for the quick response
