### ISSUE TITLE
Server crash from TileEntityDiamondCobblegen

### ISSUE THREAD

**Issue by IchigoGames** [Kashdeya/SimpleUpgrades#37]
my server today has crashed like 6 or 7 times from one of the items in your mod here is the crash report and  log and one forge and mod version i'm using.

forge-1.10.2-12.18.0.2008
simpleupgrades-1.10.0-2.0.11-release

https://www.dropbox.com/s/n85xntgqhl5n2zh/crash-2016-07-09_18.04.38-server.txt?dl=0

https://www.dropbox.com/s/deeie19ag5hyjjr/fml-server-latest.log?dl=0

**Comment by Kashdeya** [comment]
I will take a look at this.

**Comment by Shadows-of-Fire** [comment]
There's also an error on the lowest tier of cobble generator, and most likely the middle.  
https://gist.github.com/Shadows-of-Fire/0cf33f72d8d73dd6652f867cd9e9fc4d
Don't know if its the same as the above crash, since those links lead nowhere.

**Comment by fr0st6yt3** [comment]
Has there been an update on this yet? I am still having issues with this crashing.

**Comment by Kashdeya** [comment]
this has been fixed in the next update. no eta on release as of yet.
