### ISSUE TITLE
server crash during world creation

### ISSUE THREAD

**Issue by Sailren** [Kashdeya/SimpleUpgrades#41]
this crash happens with the testing release from curseforge for mc version 1.10.2

http://paste.ubuntu.com/23068062/

**Comment by jsaggers** [comment]
I had this same problem which can be fixed via going into the config folder, simple upgrades folder and in the worldgen.cfg file there are six options you need to set to false.
"BaseMetals Support"=false
"Dense BaseMetals Ores"=false
"Dense End BaseMetals Ores"=false
"Dense Nether BaseMetals Ores"=false
"End BaseMetals Ores"=false
"Nether BaseMetals Ores"=false
They are all at the top of the file. This worked for me.

**Comment by Kashdeya** [comment]
fixed in 2.1.3
