### ISSUE TITLE
TileEntityCobblegen

### ISSUE THREAD

**Issue by Diamond-anvil** [Kashdeya/SimpleUpgrades#42]
I seam to be having trouble with the Dark Grid pack when placing a Cobblegen in the world MC crashes and throws this error: java.lang.RuntimeException: class com.kashdeya.simpleupgrades.tileentity.TileEntityCobblegen is missing a mapping! This is a bug!

[Crash Report](http://pastebin.com/AwRzJCkB): http://pastebin.com/AwRzJCkB

**Comment by Kashdeya** [comment]
fixed in 2.1.3
