### ISSUE TITLE
Broken recipes

### ISSUE THREAD

**Issue by mobehun** [Kashdeya/SimpleUpgrades#43]
Version: simpleupgrades-1.10.2-2.1.1-testing-release
Forge: forge-12.18.1.2061
Issue: Some of the recipes are gone. The armors are not craftable and the dense ores drops themselves. Same with the nether and end variants. Some of the ores show up in JEI as "tile.null.name" and when broken drops the smelted form (no auto smelt on pickaxe).

**Comment by mobehun** [comment]
Latest version (simpleupgrades-1.10.2-2.1.2-Beta-release) fixed these issues but some of the ores (dense, nether, end variants) still drops the smelted variants.
Is that intended?

**Comment by Ceruleann** [comment]
same here, and I cannot craft the wooden tools (pickaxe, axe... etc).

**Comment by mobehun** [comment]
> same here, and I cannot craft the wooden tools (pickaxe, axe... etc).
^That is a config option.

**Comment by Kashdeya** [comment]
fixed in 2.1.3
