### ISSUE TITLE
Swords don't accept sword enchantments.

### ISSUE THREAD

**Issue by Mach12** [Kashdeya/SimpleUpgrades#45]
'Nuff said I think. You can't enchant things like the obsidian or diamond infused swords with anything but unbreaking and mending (and hypermending but that's modded content).
Basically you can give it any enchantment you'd give to flint and steel, no more.

Did you not extend a base Sword class or something?

P.S: All your issues are closed, woah :o Some mod devs could learn from you

**Comment by Kashdeya** [comment]
I will take a look at this during the next update.

**Comment by Kashdeya** [comment]
Update will be out shortly.
