### ISSUE TITLE
Ore Gen and Harvesting.

### ISSUE THREAD

**Issue by RebeccaRedstone** [Kashdeya/SimpleUpgrades#46]
Possible bugs found with Simple Upgrades v 1.10.2 - 2.1.14 (using forge- 2073)

I found condensed diamond and condensed lapis between levels 54-50.

WAILA harvestability says harvest level is diamond for both ruby and sapphire - however they can be harvested with stone.

**Comment by Kashdeya** [comment]
Thank you this will be looked at before next update.

**Comment by Kashdeya** [comment]
issue has been fixed.
