### ISSUE TITLE
Amethyst Dust

### ISSUE THREAD

**Issue by mobehun** [Kashdeya/SimpleUpgrades#47]
Amethyst Dust is only smelt-able by the Arc Furnace.
http://prnt.sc/chjla3
simpleupgrades-1.10.2-2.1.4-release

**Comment by Kashdeya** [comment]
is your pack on Curse? if so can you tell me the name so that I can download it and test the mod updates in the pack.

**Comment by mobehun** [comment]
https://minecraft.curseforge.com/projects/brave-technology-new-world

**Comment by mobehun** [comment]
Use the release versions of the pack.

**Comment by Kashdeya** [comment]
so 1.10 1.16?

**Comment by mobehun** [comment]
Yes. An update should be up later today, depending on my time.

**Comment by Kashdeya** [comment]
issue has been fixed
