### ISSUE TITLE
Diamond infused pickaxe won't mine

### ISSUE THREAD

**Issue by Physaliidae** [Kashdeya/SimpleUpgrades#48]
Using simpleupgrades-1.10.2-2.1.4-release and the diamond infused pickaxe won't mine anything. Particles come out but the blocks simply don't break (like bedrock). This is true for all materials I have tested the pickaxe on. Also have tried creative mode adding it to my inventory but it still breaks nothing in survival. 

I am running several other mods (biomes o plenty, quark, etc.) but I am fairly sure none of them are interfering.

**Comment by Kashdeya** [comment]
1. you can not break bedrock with any of the pickaxes in the mod. 
2. is your pack on curse so that i can download and see the problem first hand?

**Comment by Kashdeya** [comment]
Issue has been fixed.

**Comment by Physaliidae** [comment]
Thank you!
