### ISSUE TITLE
Cobblegen name conflict withTiny Progressions

### ISSUE THREAD

**Issue by charlesbevans** [Kashdeya/SimpleUpgrades#49]
I was trying out some new mods and discovered that both SimpleUpgrades and Tiny Progressions introduce an item called cobblegen_block. 

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tiny Progressions (tp)
Caused by: java.lang.IllegalArgumentException: Duplicate id: tileEntityCobblegen

Would you consider refactoring the name or including a config to completely disable the item? (sucobblegen or tp cobblegen?)

**Comment by Kashdeya** [comment]
Closed see https://github.com/Kashdeya/Tiny-Progressions/issues/6
