### ISSUE TITLE
Diamond Hammer on Forge 1865 server

### ISSUE THREAD

**Issue by kwpugh** [Kashdeya/SimpleUpgrades#6]
Hi,

When you use the diamond hammer to make obsidian dust in a crafting table, you get the first piece of dust.   Then the texture of the hammer turns purple/black and no longer works.

To install the v1.0.6, I followed directions to delete the config folder first, and a new folder was created with the four config files.   This behavior also happens in single player as well.

No errors on the console are recorded.

See screenshots for before and after

![before](https://cloud.githubusercontent.com/assets/8809210/14711703/08777d82-07a0-11e6-8be9-2d0ff379e57b.jpg)

![after](https://cloud.githubusercontent.com/assets/8809210/14711709/0e977b72-07a0-11e6-9e0f-c4e8a5c4685f.jpg)

**Comment by kwpugh** [comment]
I re-tested with v1.0.5 on SP and server and it worked fine there, broken on v1.0.6.

**Comment by Kashdeya** [comment]
Looking into it now.

**Comment by The-Euphoria** [comment]
Yep, I was just about to report this too.

Also, apologies I'm not trying to hijack the thread but to save opening a new report, "Dense Lapis" is also broken with 1.0.6. The texture when in-hand and in the inventory is missing same as the hammer.

**Comment by Kashdeya** [comment]
Are you using a texture/resource pack?

**Comment by kwpugh** [comment]
No texture pack or resource pack, just the default.

**Comment by kwpugh** [comment]
It's not just the visual, the item no longer works, its like it is not accounting for durability loss or something, or all durability is loss.

**Comment by Kashdeya** [comment]
Yeah the hammer has been fixed in next update. what about the Lapis? cause it all seems to work in my dev world. But I will start a new instance and see if i can dupe the problem.
