### ISSUE TITLE
A few crashes for different reasons

### ISSUE THREAD

**Issue by CorGaming** [Kashdeya/SimpleUpgrades#9]
In the following crash I dont understand what I did wrong...I disabled a few itens, including dense ores (only in the nether)
[crash-2016-04-29_17.25.36-server.txt](https://github.com/Kashdeya/SimpleUpgrades/files/242853/crash-2016-04-29_17.25.36-server.txt)

In this one I disabled ALL dense ore, and all colored things and all deco.
[crash-2016-04-29_17.28.40-server.txt](https://github.com/Kashdeya/SimpleUpgrades/files/242856/crash-2016-04-29_17.28.40-server.txt)

In this last one I think the problem was with chicken shedding...you say the interval is between 0-X, but if I put 0 it doenst work...needs to be at least 1. (all the shedding options before this were set to false)
[crash-2016-04-29_17.34.25-server.txt](https://github.com/Kashdeya/SimpleUpgrades/files/242857/crash-2016-04-29_17.34.25-server.txt)

So all this problems dont occur when I have the configs vanilla. When I tried to disabled here and there the server started to crash. I dont know if some options depend on others and if so, you should add that in the comments of the configs :). I restarted server every time with new world, so that the world gen wouldnt be the problem.

If the problem is with another mod compatibility, I dont understand why with vanilla configs it works fine x).

Otherwise your mode is quite awesome and super well documented ^^.

**Comment by Kashdeya** [comment]
Can not produce the same problems. will reopen if problem shows back up.
